repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
    -   id: end-of-file-fixer
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v1.4.4
    hooks:
    -   id: autopep8
        args: [--in-place, --max-line-length=120]
-   repo: https://github.com/PyCQA/flake8
    rev: 3.7.8
    hooks:
    -   id: flake8
        args: [--max-line-length=120]
  
